using Pkg

Pkg.add(Pkg.PackageSpec(url="https://github.com/Hydro-Umass/Sad.jl"))
Pkg.add("ArgParse")
Pkg.add("PackageCompiler")
Pkg.add("Distributions")
Pkg.add("NCDatasets")
Pkg.add("JSON")
Pkg.add("PyCall")
Pkg.add("DataInterpolations")
Pkg.add("DelimitedFiles")
Pkg.add("DifferentialEquations")
Pkg.add("LinearAlgebra")
Pkg.add("Statistics")
Pkg.add("ProgressMeter")
Pkg.precompile()
